version: "3.3"
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ad_board
      POSTGRES_USER: ad_board_user
      POSTGRES_PASSWORD: ad_board_pass
    restart: always
  redis:
    image: redis
    restart: always
  api-server:
    build: .
    command: sh -c "python init_db.py && python -m api.main"
    ports:
      - 8001:8001
    depends_on:
      - db
      - redis
    restart: always