postgres:
  database: ad_board
  user: ad_board_user
  password: ad_board_pass
  host: db
  port: 5432
  minsize: 1
  maxsize: 5
redis:
  host: redis
  port: 6379
posts_per_page: 10
max_posts_per_page: 50